apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zk-deployment-1
spec:
  template:
    metadata:
      labels:
        app: zk-1
    spec:
    replicas: 1
      containers:
      - name: zk1
        image: XXX # needs to be overridden by environments
        ports:
        - containerPort: 2181
        env:
        - name: ZOOKEEPER_ID
          value: "1"
        - name: ZOOKEEPER_SERVER_1
          value: zk1
        
