apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk1 # necessary for Kustomize identification
spec:
  template:
    spec:
      containers:
      - image: bitnami/zookeeper
        name: zk1 # necessary for Kustomize identification
